language: php
dist: trusty
php:
    - 7.0
    - 7.1
install: composer install
script: "./run_tests.sh"
before_deploy: php build_phar.php
deploy:
    provider: releases
    api_key:
        secure: xCeUHwx0yuhtdgpVtT3GhQ6NoPQ657nwEUf8ouv2PXK7Aqp9bZ9+UKudKW0157L86uDJIQ5C0/4sLOksW3S2LDL5phO33OIdrlO7liNDQiRt8ccNRF76Y1pCwEEtDw9SJQfGS8DJ6zZq8Cvgu6yropeOT3XAOVcOzN9NetH4QsaQAfkdj9QIiFYKit1ea58CIqkrQqUWEkzbYwCRTcWbeVwT8UxyEnYaJUzxVnLN/u09N9xKxD385nYRxQgzPH4+MQN0fKFpP+85NGme4SMvTHxAxgIR7o6OqyVdIUiNhd3U8kYcW3SE6vBnGYiYPBUldSMMJv5ofW7gwzk04lBcYG3r6HrxNBhJWlJTcymsmdXZZ0Kz4Pbwk2bKWlye/JdZjxtjjV3rPW2BE51WGuIhsP5NQjcEq8Ebre/C0Hr6OgByqNYLZvMvUwwyEqNaZ8kpjeY2He8xsWJ/e9nvXNDUStQ2sTtVi6c0HcCUNsVrhUL9rr11fuC1Ey+73IZQNyYywLFCynKY43LbLopPRodzAw6819VbllQ9lVRQpgRsHjtj1Eo0Bs2afyQUx5sozQLcXCh1s30+0y2DHu4tS2vDH3aKQGOc9BTm3wouUjYvIEbrH9zQtYsPg9IhdaYyRKrHrLzkBVhZ+qWz3TzaOm+BeYu99n7Xxk44YYIPIlpiRbs=
    file: dicto.phar
    skip_cleanup: true
    on:
        php: 7.0
        tags: true
        repo: lechimp-p/dicto.php
